"""
Created on Sat Mar  7 08:48:27 2020

@author: SamKoebrich
"""

N_GENERATORS = 10

MULTIPROCESSING = True

WORKERS = 10 

BUFFERS = [1e2, 1e3, 1e4, 1e5]

EARTHENGINE_DBS = [
    "COPERNICUS/S5P/OFFL/L3_NO2",
    "COPERNICUS/S5P/OFFL/L3_SO2",
    "COPERNICUS/S5P/OFFL/L3_HCHO",
    "COPERNICUS/S5P/OFFL/L3_CO",
    "COPERNICUS/S5P/OFFL/L3_O3",
    "CIESIN/GPWv411/GPW_Population_Count",
    "ECMWF/ERA5/DAILY"
]